@startuml options
left to right direction
actor User as u

rectangle "Paramétrer l'application dans les options" {
usecase "Se connecter /\ndéconnecter" as UC1
usecase "Autostart les\npauses" as UC2
usecase "AutoStart les\npomodoro" as UC3
usecase "Auto Restart les\ncycles" as UC4
usecase "Activer les\nnotifications" as UC5
usecase "Activer/configurer\nles rappels" as UC6
}

u -- UC1
u -- UC2
u -- UC3
u -- UC4
u -- UC5
u -- UC6

@enduml
