@startuml pomodoro
left to right direction
actor User as u
actor "User connecté" as uc

uc --|> u

rectangle "Application Pomodoro" {
  usecase "Démarrer\nle timer" as UC1 #FF6B6B
  usecase "Pause" as UC2 #FF6B6B
  usecase "Arrêter le\ntimer" as UC3 #FF6B6B
  usecase "Réinitialiser\nle timer" as UC4 #87CEEB
  usecase "Sélectionner\nun template" as UC5 #87CEEB
  usecase "Ajouter\nune tâche" as UC6 #87CEEB
  usecase "Estimer le\ntemps" as UC7 #87CEEB
  usecase "Afficher les\ntemplates" as UC8 #87CEEB
  usecase "Sélectionner\nla tâche\nactive" as UC9 #87CEEB
  usecase "Supprimer\nune tâche" as UC10 #87CEEB
  usecase "Valider une\ntâche" as UC11 #87CEEB
  usecase "Modifier une tâche" as UC12 #87CEEB
  usecase "Sauvegarder\nun template" as UC13 #87CEEB
  usecase "Modifier\nun\ntemplate" as UC14 #87CEEB
  usecase "Supprimer\nun\ntemplate" as UC15 #87CEEB
  usecase "Dupliquer un\ntemplate" as UC16 #87CEEB
  usecase "Modifier profil" as UC17 #87CEEB
  usecase "Consulter nombre\nde tâches finies" as UC18 #FFA500
  usecase "Consulter temps\nde travail & pause" as UC19 #FFA500
  usecase "Consulter\nl'historique des\ntâches et leur\ntemps dédié" as UC20 #FFA500
  usecase "Activer les\nnotifications" as UC21 #FFA500
  usecase "Mode ne pas\ndéranger" as UC22 #FFA500
  usecase "Sélectionner le\nstyle de\nl'application" as UC24 #DDA0DD
  usecase "Personnalisation\ndes sons\nd'alarmes" as UC25 #DDA0DD
  
}

' User connections
u --> UC1
u --> UC5
u --> UC6
u --> UC8
u --> UC9
u --> UC10
u --> UC11
u --> UC12

' User connecté connections
uc --> UC13
uc --> UC14
uc --> UC15
uc --> UC16
uc --> UC18
uc --> UC19
uc --> UC20
uc --> UC17
uc --> UC21
uc --> UC25
uc --> UC22
uc --> UC24

' Relations extends
UC1 ..> UC2 : <<Extends>>
UC1 ..> UC3 : <<Extends>>
UC1 ..> UC4 : <<Extends>>
UC1 ..> UC5 : <<Extends>>
UC6 <.. UC7 : <<Extends>>

@enduml