@startuml pomodoro_domain
left to right direction

class User {
  +email : string
  +name : string
  +password : string
}

class Parameters {
  +autostartWork : bool
  +autostartRest : bool
  +autoRestartCycle : bool
  +notificationsOn : bool
}

class Task {
  +title : string
  +description : string
  +estimatedTime : int
  +status : TaskStatus
  +creationDate : DateTime
  +endDate : DateTime
}

class History {
  +workTime: int
  +restTime: int
}
class Cycle {
  +name : string
}

class Period {
  +type : PeriodType
  +time : int
}

' Relations

User "1" -- "1" Parameters

User "1" -- "0..*" Task
User "1" -- "0..*" Cycle
User "1" -- "0..*" History
Cycle "1" -- "1..*" Period

@enduml
